TASK 9

In [41]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

READ

In [42]:
df = pd.read_csv(r"d:\ARTIFICIAL INTELLIGENCE\3RD SEMESTER BSAI\AI LAB\LAB 10\Student_Marks.csv")
df

number_courses  time_study   Marks Grade
0                3       4.508  19.202     F
1                4       0.096   7.734     F
2                4       3.133  13.811     F
3                6       7.909  53.018     D
4                8       7.811  55.299     D
..             ...         ...     ...   ...
95               6       3.561  19.128     F
96               3       0.301   5.609     F
97               4       7.163  41.444     F
98               7       0.309  12.027     F
99               3       6.335  32.357     F

[100 rows x 4 columns]

EXPLORE

In [43]:
print(f"Number of Rows: {df.shape[0]}\nNumber of Columns: {df.shape[1]}")

Number of Rows: 100
Number of Columns: 4


In [44]:
df.head(2)

number_courses  time_study   Marks Grade
0               3       4.508  19.202     F
1               4       0.096   7.734     F

In [45]:
df.tail(2)

number_courses  time_study   Marks Grade
98               7       0.309  12.027     F
99               3       6.335  32.357     F

In [46]:
df.describe()

number_courses  time_study       Marks
count      100.000000  100.000000  100.000000
mean         5.290000    4.040434   24.467707
std          1.799523    2.344353   14.317465
min          3.000000    0.096000    5.609000
25%          4.000000    2.058500   12.633000
50%          5.000000    4.008717   20.373000
75%          7.000000    6.137750   36.676250
max          8.000000    7.957000   55.299000

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   number_courses  100 non-null    int64  
 1   time_study      100 non-null    float64
 2   Marks           100 non-null    float64
 3   Grade           100 non-null    object 
dtypes: float64(2), int64(1), object(1)
memory usage: 3.3+ KB


In [48]:
df.columns

Index(['number_courses', 'time_study', 'Marks', 'Grade'], dtype='object')

In [49]:
for i in df.columns:
    print(i)

number_courses
time_study
Marks
Grade


In [50]:
df.count()

number_courses    100
time_study        100
Marks             100
Grade             100
dtype: int64

In [51]:
df.isnull().sum()

number_courses    0
time_study        0
Marks             0
Grade             0
dtype: int64

TASK 10 

DATA PREPROCESSING 

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   number_courses  100 non-null    int64  
 1   time_study      100 non-null    float64
 2   Marks           100 non-null    float64
 3   Grade           100 non-null    object 
dtypes: float64(2), int64(1), object(1)
memory usage: 3.3+ KB


In [53]:
df.isnull().sum()

number_courses    0
time_study        0
Marks             0
Grade             0
dtype: int64

DEALING WITH NULL VALUES

In [54]:
def fillNaMean(cols):
    for i in cols:
        df[i] = df[i].fillna(df[i].mean())

columns = ['time_study', 'Marks']
fillNaMean(columns)

In [55]:
def fillNaMode(cols):
    for i in cols:
        df[i] = df[i].fillna(df[i].mode()[0])

columns = ['number_courses']
fillNaMode(columns)

In [56]:
df.isnull().sum()

number_courses    0
time_study        0
Marks             0
Grade             0
dtype: int64

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   number_courses  100 non-null    int64  
 1   time_study      100 non-null    float64
 2   Marks           100 non-null    float64
 3   Grade           100 non-null    object 
dtypes: float64(2), int64(1), object(1)
memory usage: 3.3+ KB


DROPING IRRELIVANT 

In [58]:
df.drop('Grade', axis=1, inplace=True)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   number_courses  100 non-null    int64  
 1   time_study      100 non-null    float64
 2   Marks           100 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB


In [60]:
def changeFloattoInt64(cols):
    for i in cols:
        df[i] = df[i].astype('int64')

columns = ['number_courses', 'time_study', 'Marks']
changeFloattoInt64(columns)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   number_courses  100 non-null    int64
 1   time_study      100 non-null    int64
 2   Marks           100 non-null    int64
dtypes: int64(3)
memory usage: 2.5 KB


In [62]:
df['Marks'].unique()

array([19,  7, 13, 53, 55, 17, 29, 20, 30, 42, 12, 24, 11, 38, 50, 25, 22,
       35, 28, 16,  6, 26,  9,  8, 15, 39, 43, 46, 41, 51, 10, 40, 36, 18,
       31, 21, 27, 49, 54, 44, 23,  5, 32], dtype=int64)

In [63]:
df['number_courses'].unique()

array([3, 4, 6, 8, 5, 7], dtype=int64)

In [64]:
df['time_study'].unique()

array([4, 0, 3, 7, 6, 2, 5, 1], dtype=int64)

In [65]:
df_clean = df.copy()

In [66]:
df_clean.head()

number_courses  time_study  Marks
0               3           4     19
1               4           0      7
2               4           3     13
3               6           7     53
4               8           7     55

In [67]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   number_courses  100 non-null    int64
 1   time_study      100 non-null    int64
 2   Marks           100 non-null    int64
dtypes: int64(3)
memory usage: 2.5 KB


In [68]:
df_clean.to_csv(r'cleaned-data-new.csv', index=False, header=True)

In [69]:
df_clean.head(2)

number_courses  time_study  Marks
0               3           4     19
1               4           0      7

TASK 11

DATA SPLITTING/TRAIN_TEST_SPLIT 

In [70]:
X = df_clean[['number_courses', 'time_study']]  
y = df_clean['Marks']                           

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,)

In [72]:
X_train.head(2)

number_courses  time_study
25               3           1
58               3           6

In [73]:
y_train.head(2)

25     6
58    31
Name: Marks, dtype: int64

In [74]:
print("TrainX:",X_train.shape)
print("TrainY:",y_train.shape)
print("TestX:",X_test.shape)
print("TestY:",y_test.shape)

TrainX: (80, 2)
TrainY: (80,)
TestX: (20, 2)
TestY: (20,)


TRAINING

In [75]:
import pickle
from sklearn.svm import SVR

In [81]:
model_SVR = SVR()
model_SVR.fit(X_train, y_train)
pickle.dump(model_SVR, open('model_SVR.pkl', 'wb'))
print(model_SVR)

SVR()


In [84]:
model_SVR = pickle.load(open('model_SVR.pkl', 'rb'))
svc_predictions = model_SVR.predict(X_test)

In [85]:
print(svr_predictions)

[16.54334525 37.13032485 29.10022952 17.33986177  9.45880598 35.51161259
 31.3458283  26.34724353 26.34724353 17.33986177 10.29000053 19.2360224
 19.150793   19.2360224  15.89962182 19.150793   15.89962182 25.43300015
  9.45880598 22.48629747]


In [86]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, svr_predictions)
print("Mean Squared Error (MSE): {:.2f}".format(mse))


Mean Squared Error (MSE): 21.04


In [87]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, svr_predictions)
print("R2 Score (Accuracy): {:.2f}".format(r2 * 100), "%")


R2 Score (Accuracy): 84.63 %
