TASK 9

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

READ

In [2]:
df = pd.read_csv(r"d:\ARTIFICIAL INTELLIGENCE\3RD SEMESTER BSAI\AI LAB\LAB 10\Student_Marks.csv")
df

number_courses  time_study   Marks Grade
0              3.0       4.508  19.202     B
1              4.0       0.096   7.734     C
2              4.0       3.133  13.811     A
3              6.0       7.909  53.018     B
4              8.0       7.811  55.299     C
..             ...         ...     ...   ...
95             6.0       3.561  19.128     A
96             3.0       0.301   5.609     B
97             4.0       7.163  41.444     F
98             7.0       0.309  12.027     C
99             3.0       6.335  32.357     A

[100 rows x 4 columns]

EXPLORE

In [3]:
print(f"Number of Rows: {df.shape[0]}\nNumber of Columns: {df.shape[1]}")

Number of Rows: 100
Number of Columns: 4


In [4]:
df.head(2)

number_courses  time_study   Marks Grade
0             3.0       4.508  19.202     B
1             4.0       0.096   7.734     C

In [5]:
df.tail(2)

number_courses  time_study   Marks Grade
98             7.0       0.309  12.027     C
99             3.0       6.335  32.357     A

In [6]:
df.describe()

number_courses  time_study      Marks
count       99.000000   99.000000  99.000000
mean         5.313131    4.040434  24.467707
std          1.793676    2.356284  14.390328
min          3.000000    0.096000   5.609000
25%          4.000000    2.056000  12.619000
50%          5.000000    3.977000  20.348000
75%          7.000000    6.149500  36.699500
max          8.000000    7.957000  55.299000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   number_courses  99 non-null     float64
 1   time_study      99 non-null     float64
 2   Marks           99 non-null     float64
 3   Grade           100 non-null    object 
dtypes: float64(3), object(1)
memory usage: 3.3+ KB


In [8]:
df.columns

Index(['number_courses', 'time_study', 'Marks', 'Grade'], dtype='object')

In [9]:
for i in df.columns:
    print(i)

number_courses
time_study
Marks
Grade


In [10]:
df.count()

number_courses     99
time_study         99
Marks              99
Grade             100
dtype: int64

In [11]:
df.isnull().sum()

number_courses    1
time_study        1
Marks             1
Grade             0
dtype: int64

TASK 10 

DATA PREPROCESSING 

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   number_courses  99 non-null     float64
 1   time_study      99 non-null     float64
 2   Marks           99 non-null     float64
 3   Grade           100 non-null    object 
dtypes: float64(3), object(1)
memory usage: 3.3+ KB


In [13]:
df.isnull().sum()

number_courses    1
time_study        1
Marks             1
Grade             0
dtype: int64

DEALING WITH NULL VALUES

In [14]:
def fillNaMean(cols):
    for i in cols:
        df[i] = df[i].fillna(df[i].mean())

columns = ['time_study', 'Marks']
fillNaMean(columns)

In [15]:
def fillNaMode(cols):
    for i in cols:
        df[i] = df[i].fillna(df[i].mode()[0])

columns = ['number_courses']
fillNaMode(columns)

In [16]:
df.isnull().sum()

number_courses    0
time_study        0
Marks             0
Grade             0
dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   number_courses  100 non-null    float64
 1   time_study      100 non-null    float64
 2   Marks           100 non-null    float64
 3   Grade           100 non-null    object 
dtypes: float64(3), object(1)
memory usage: 3.3+ KB


DROPING IRRELIVANT 

In [18]:
df.drop('Grade', axis=1, inplace=True)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   number_courses  100 non-null    float64
 1   time_study      100 non-null    float64
 2   Marks           100 non-null    float64
dtypes: float64(3)
memory usage: 2.5 KB


In [20]:
def changeFloattoInt64(cols):
    for i in cols:
        df[i] = df[i].astype('int64')

columns = ['number_courses', 'time_study', 'Marks']
changeFloattoInt64(columns)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   number_courses  100 non-null    int64
 1   time_study      100 non-null    int64
 2   Marks           100 non-null    int64
dtypes: int64(3)
memory usage: 2.5 KB


In [22]:
df['Marks'].unique()

array([19,  7, 13, 53, 55, 17, 29, 20, 30, 42, 12, 24, 11, 38, 50, 25, 22,
       35, 28, 16,  6, 26,  9,  8, 15, 39, 43, 46, 41, 51, 10, 40, 36, 18,
       31, 21, 27, 49, 54, 44, 23,  5, 32], dtype=int64)

In [23]:
df['number_courses'].unique()

array([3, 4, 6, 8, 5, 7], dtype=int64)

In [24]:
df['time_study'].unique()

array([4, 0, 3, 7, 6, 2, 5, 1], dtype=int64)

In [25]:
df_clean = df.copy()

In [26]:
df_clean.head()

number_courses  time_study  Marks
0               3           4     19
1               4           0      7
2               4           3     13
3               6           7     53
4               8           7     55

In [27]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   number_courses  100 non-null    int64
 1   time_study      100 non-null    int64
 2   Marks           100 non-null    int64
dtypes: int64(3)
memory usage: 2.5 KB


In [30]:
# Save the cleaned dataframe to a new file
df_clean.to_csv(r'cleaned-data-new.csv', index=False, header=True)

In [31]:
df_clean.head(2)

number_courses  time_study  Marks
0               3           4     19
1               4           0      7

TASK 11

DATA SPLITTING/TRAIN_TEST_SPLIT 

In [ ]:
X = df_clean[['number_courses', 'time_study']]  
y = df_clean['Marks']                           

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,)

In [34]:
X_train.head(2)

number_courses  time_study
55               7           2
95               6           3

In [35]:
y_train.head(2)

55    18
95    19
Name: Marks, dtype: int64

In [36]:
print("TrainX:",X_train.shape)
print("TrainY:",y_train.shape)
print("TestX:",X_test.shape)
print("TestY:",y_test.shape)

TrainX: (80, 2)
TrainY: (80,)
TestX: (20, 2)
TestY: (20,)


TRAINING

In [37]:
import pickle
from sklearn.svm import SVR

In [38]:
model_SVR = SVR()
model_SVR.fit(X_train, y_train)

print(model_SVR)

SVR()


In [39]:
svr_predictions = model_SVR.predict(X_test)

In [40]:
print(svr_predictions)

[25.23116092 19.15312551 29.10031675 13.66717467  9.63022956 26.88780996
 31.29413828  8.7776228  16.77659788 17.14185404 36.98487344 20.89021432
 29.27054059  9.89273286 14.3386147  36.98487344 15.89977928 17.14185404
 20.89021432 21.70539367]


In [41]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, svr_predictions)
print("Mean Squared Error (MSE): {:.2f}".format(mse))


Mean Squared Error (MSE): 24.05


In [42]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, svr_predictions)
print("R2 Score (Accuracy): {:.2f}".format(r2 * 100), "%")


R2 Score (Accuracy): 83.91 %
