In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

DATA LOADING 

In [ ]:
df = pd.read_csv(r"music-dataset.csv")
df

Song            Artist    Streams  Daily Streams         Genre  \
0     Track 14728          Jungkook  410000000         550000           Pop   
1     Track 21319          Jungkook  370000000         520000    Pop/Ballad   
2     Track 21324                RM  300000000         370000   Alt/Hip-Hop   
3     Track 21325   J-Hopeft.J.Cole  720000000         950000       Hip-Hop   
4     Track 21326             Jimin  680000000         800000  Experimental   
...           ...               ...        ...            ...           ...   
4845  Track 24875  Aurora Soundwave  439001503         391466         Indie   
4846   Track 7493      Samantha Lee  272411120        4270641         Metal   
4847  Track 61735   Retro Resonance  590393937        1474438         K-Pop   
4848  Track 47314        Bass Surge  376858259        1933465         Latin   
4849  Track 30934      Shadow Beats  262207213        2419058         Blues   

      Release Year  Peak Position  Weeks on Chart Lyrics Sentiment  \
0             2023             11           110.0           Flirty   
1             2023             13           100.0      Bittersweet   
2             2024             15            40.0           Honest   
3             2023              5            24.0        Gratitude   
4             2023              3            77.0          Intense   
...            ...            ...             ...              ...   
4845          2003             59            18.0        Gratitude   
4846          2004             96             1.0             Duet   
4847          2014             55            27.0             Duet   
4848          1996             75            15.0        Confident   
4849          2006             15            57.0           Flirty   

      TikTok Virality  Danceability  Acousticness  Energy  
0                77.0          0.77          0.22    0.76  
1                98.0          0.58          0.30    0.60  
2                65.0          0.65          0.35    0.60  
3                73.0          0.78          0.22    0.75  
4                49.0          0.82          0.14    0.88  
...               ...           ...           ...     ...  
4845             54.0          0.66          0.54    0.73  
4846             94.0          0.77          0.50    0.19  
4847              9.0          0.91          0.83    0.91  
4848             31.0          0.17          0.03    0.79  
4849             86.0          0.51          0.73    0.49  

[4850 rows x 13 columns]

DATA EXPLOARATION 

In [ ]:
print(f"Number of Rows: {df.shape[0]}\nNumber of Columns: {df.shape[1]}")

Number of Rows: 4850
Number of Columns: 13


In [ ]:
df.head(2)

Song    Artist    Streams  Daily Streams       Genre  Release Year  \
0  Track 14728  Jungkook  410000000         550000         Pop          2023   
1  Track 21319  Jungkook  370000000         520000  Pop/Ballad          2023   

   Peak Position  Weeks on Chart Lyrics Sentiment  TikTok Virality  \
0             11           110.0           Flirty             77.0   
1             13           100.0      Bittersweet             98.0   

   Danceability  Acousticness  Energy  
0          0.77          0.22    0.76  
1          0.58          0.30    0.60

In [ ]:
df.tail(2)

Song        Artist    Streams  Daily Streams  Genre  \
4848  Track 47314    Bass Surge  376858259        1933465  Latin   
4849  Track 30934  Shadow Beats  262207213        2419058  Blues   

      Release Year  Peak Position  Weeks on Chart Lyrics Sentiment  \
4848          1996             75            15.0        Confident   
4849          2006             15            57.0           Flirty   

      TikTok Virality  Danceability  Acousticness  Energy  
4848             31.0          0.17          0.03    0.79  
4849             86.0          0.51          0.73    0.49

In [ ]:
df.describe()

Streams  Daily Streams  Release Year  Peak Position  \
count  4.850000e+03   4.850000e+03   4850.000000    4850.000000   
mean   3.978190e+08   2.486865e+06   2007.798969      51.171340   
std    2.306049e+08   1.458966e+06     10.369170      29.027911   
min    1.130883e+06   1.158000e+04   1990.000000       0.000000   
25%    1.993923e+08   1.194214e+06   1999.000000      26.000000   
50%    3.947976e+08   2.471572e+06   2008.000000      51.000000   
75%    5.986818e+08   3.779586e+06   2017.000000      76.000000   
max    8.500000e+08   4.999643e+06   2025.000000     100.000000   

       Weeks on Chart  TikTok Virality  Danceability  Acousticness      Energy  
count     4849.000000      4849.000000   4848.000000   4849.000000  4847.00000  
mean        52.231388        50.809858      0.585283      0.499961     0.55294  
std         29.466280        29.287534      1.451846      0.287479     0.26073  
min          0.000000         0.000000      0.000000      0.000000     0.00000  
25%         27.000000        26.000000      0.330000      0.250000     0.32000  
50%         52.000000        51.000000      0.565000      0.500000     0.56000  
75%         78.000000        76.000000      0.780000      0.750000     0.77000  
max        110.000000       100.000000     71.000000      1.000000     1.00000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4850 entries, 0 to 4849
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Song              4850 non-null   object 
 1   Artist            4850 non-null   object 
 2   Streams           4850 non-null   int64  
 3   Daily Streams     4850 non-null   int64  
 4   Genre             4850 non-null   object 
 5   Release Year      4850 non-null   int64  
 6   Peak Position     4850 non-null   int64  
 7   Weeks on Chart    4849 non-null   float64
 8   Lyrics Sentiment  4850 non-null   object 
 9   TikTok Virality   4849 non-null   float64
 10  Danceability      4848 non-null   float64
 11  Acousticness      4849 non-null   float64
 12  Energy            4847 non-null   float64
dtypes: float64(5), int64(4), object(4)
memory usage: 492.7+ KB


In [ ]:
df.columns

Index(['Song', 'Artist', 'Streams', 'Daily Streams', 'Genre', 'Release Year',
       'Peak Position', 'Weeks on Chart', 'Lyrics Sentiment',
       'TikTok Virality', 'Danceability', 'Acousticness', 'Energy'],
      dtype='object')

In [ ]:
for i in df.columns:
    print(i)

Song
Artist
Streams
Daily Streams
Genre
Release Year
Peak Position
Weeks on Chart
Lyrics Sentiment
TikTok Virality
Danceability
Acousticness
Energy


In [ ]:
df.count()

Song                4850
Artist              4850
Streams             4850
Daily Streams       4850
Genre               4850
Release Year        4850
Peak Position       4850
Weeks on Chart      4849
Lyrics Sentiment    4850
TikTok Virality     4849
Danceability        4848
Acousticness        4849
Energy              4847
dtype: int64

In [ ]:
df['Artist'].unique()

array(['Jungkook', 'RM', 'J-Hopeft.J.Cole', 'Jimin', 'J-Hope', 'Jin', 'V',
       'Suga', 'Jungkookft.CharliePuth', 'Sugaft.IU', 'Retro Resonance',
       'Urban Rhapsody', 'Sofia Carter', 'ElectroPulse',
       'Firefly Symphony', 'Neon Vortex', 'Liam Harper', 'Jay Zenith',
       'The Midnight Howl', 'Shadow Beats', 'Samantha Lee',
       'Aurora Soundwave', 'DJ Thunder', 'Horizon Flow', 'EchoSync',
       'Ava & The Ocean', 'Crimson Echo', 'Celestial Harmony',
       'Bass Surge', 'Luna Nova'], dtype=object)

In [ ]:
df['Genre'].unique()

array(['Pop', 'Pop/Ballad', 'Alt/Hip-Hop', 'Hip-Hop', 'Experimental',
       'Ballad', 'Soul/Pop', 'Pop/Rock', 'Pop/Soul', 'Hip-Hop/Pop',
       'Indie/Pop', 'Pop/Acoustic', 'Pop/Rap', 'Reggae', 'Blues', 'Latin',
       'Synthwave', 'Techno', 'R&B/Alt', 'Trap', 'Jazz', 'Punk', 'Rock',
       'Electronic', 'House', 'Folk', 'Retro Soul', 'Country', 'Lo-Fi',
       'Metal', 'Indie', 'Drum & Bass', 'R&B', 'K-Pop', 'EDM'],
      dtype=object)

In [ ]:
df['Artist'].unique()

array(['Jungkook', 'RM', 'J-Hopeft.J.Cole', 'Jimin', 'J-Hope', 'Jin', 'V',
       'Suga', 'Jungkookft.CharliePuth', 'Sugaft.IU', 'Retro Resonance',
       'Urban Rhapsody', 'Sofia Carter', 'ElectroPulse',
       'Firefly Symphony', 'Neon Vortex', 'Liam Harper', 'Jay Zenith',
       'The Midnight Howl', 'Shadow Beats', 'Samantha Lee',
       'Aurora Soundwave', 'DJ Thunder', 'Horizon Flow', 'EchoSync',
       'Ava & The Ocean', 'Crimson Echo', 'Celestial Harmony',
       'Bass Surge', 'Luna Nova'], dtype=object)

In [ ]:
df.nunique()

Song                4745
Artist                30
Streams             4846
Daily Streams       4843
Genre                 35
Release Year          36
Peak Position        101
Weeks on Chart       105
Lyrics Sentiment      22
TikTok Virality      101
Danceability          94
Acousticness         101
Energy                92
dtype: int64

In [ ]:
df.isnull().sum()

Song                0
Artist              0
Streams             0
Daily Streams       0
Genre               0
Release Year        0
Peak Position       0
Weeks on Chart      1
Lyrics Sentiment    0
TikTok Virality     1
Danceability        2
Acousticness        1
Energy              3
dtype: int64

DATA PREPROCESSING

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4850 entries, 0 to 4849
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Song              4850 non-null   object 
 1   Artist            4850 non-null   object 
 2   Streams           4850 non-null   int64  
 3   Daily Streams     4850 non-null   int64  
 4   Genre             4850 non-null   object 
 5   Release Year      4850 non-null   int64  
 6   Peak Position     4850 non-null   int64  
 7   Weeks on Chart    4849 non-null   float64
 8   Lyrics Sentiment  4850 non-null   object 
 9   TikTok Virality   4849 non-null   float64
 10  Danceability      4848 non-null   float64
 11  Acousticness      4849 non-null   float64
 12  Energy            4847 non-null   float64
dtypes: float64(5), int64(4), object(4)
memory usage: 492.7+ KB


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4850 entries, 0 to 4849
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Song              4850 non-null   object 
 1   Artist            4850 non-null   object 
 2   Streams           4850 non-null   int64  
 3   Daily Streams     4850 non-null   int64  
 4   Genre             4850 non-null   object 
 5   Release Year      4850 non-null   int64  
 6   Peak Position     4850 non-null   int64  
 7   Weeks on Chart    4849 non-null   float64
 8   Lyrics Sentiment  4850 non-null   object 
 9   TikTok Virality   4849 non-null   float64
 10  Danceability      4848 non-null   float64
 11  Acousticness      4849 non-null   float64
 12  Energy            4847 non-null   float64
dtypes: float64(5), int64(4), object(4)
memory usage: 492.7+ KB


In [ ]:
df.isnull().sum()

Song                0
Artist              0
Streams             0
Daily Streams       0
Genre               0
Release Year        0
Peak Position       0
Weeks on Chart      1
Lyrics Sentiment    0
TikTok Virality     1
Danceability        2
Acousticness        1
Energy              3
dtype: int64

In [ ]:
def fillNaMean(cols):
    for i in cols:
        df[i] = df[i].fillna(df[i].mean())

columns = ['Danceability', 'Acousticness', 'Energy','TikTok Virality']
fillNaMean(columns)

In [ ]:
df.isnull().sum()

Song                0
Artist              0
Streams             0
Daily Streams       0
Genre               0
Release Year        0
Peak Position       0
Weeks on Chart      1
Lyrics Sentiment    0
TikTok Virality     0
Danceability        0
Acousticness        0
Energy              0
dtype: int64

In [ ]:
def fillNaMode(cols):
    for i in cols:
        df[i] = df[i].fillna(df[i].mode()[0])

columns = ['Lyrics Sentiment']
fillNaMode(columns)

In [ ]:
df.isnull().sum()

Song                0
Artist              0
Streams             0
Daily Streams       0
Genre               0
Release Year        0
Peak Position       0
Weeks on Chart      1
Lyrics Sentiment    0
TikTok Virality     0
Danceability        0
Acousticness        0
Energy              0
dtype: int64

In [ ]:
def fillNaMedian(cols):
    for i in cols:
        df[i] = df[i].fillna(df[i].median())
columns = ['Weeks on Chart']
fillNaMedian(columns)


In [ ]:
df.isnull().sum()

Song                0
Artist              0
Streams             0
Daily Streams       0
Genre               0
Release Year        0
Peak Position       0
Weeks on Chart      0
Lyrics Sentiment    0
TikTok Virality     0
Danceability        0
Acousticness        0
Energy              0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4850 entries, 0 to 4849
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Song              4850 non-null   object 
 1   Artist            4850 non-null   object 
 2   Streams           4850 non-null   int64  
 3   Daily Streams     4850 non-null   int64  
 4   Genre             4850 non-null   object 
 5   Release Year      4850 non-null   int64  
 6   Peak Position     4850 non-null   int64  
 7   Weeks on Chart    4850 non-null   float64
 8   Lyrics Sentiment  4850 non-null   object 
 9   TikTok Virality   4850 non-null   float64
 10  Danceability      4850 non-null   float64
 11  Acousticness      4850 non-null   float64
 12  Energy            4850 non-null   float64
dtypes: float64(5), int64(4), object(4)
memory usage: 492.7+ KB


In [ ]:
df.drop('Song', axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4850 entries, 0 to 4849
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Artist            4850 non-null   object 
 1   Streams           4850 non-null   int64  
 2   Daily Streams     4850 non-null   int64  
 3   Genre             4850 non-null   object 
 4   Release Year      4850 non-null   int64  
 5   Peak Position     4850 non-null   int64  
 6   Weeks on Chart    4850 non-null   float64
 7   Lyrics Sentiment  4850 non-null   object 
 8   TikTok Virality   4850 non-null   float64
 9   Danceability      4850 non-null   float64
 10  Acousticness      4850 non-null   float64
 11  Energy            4850 non-null   float64
dtypes: float64(5), int64(4), object(3)
memory usage: 454.8+ KB


In [ ]:
def changeFloattoInt64(cols):
    for i in cols:
        df[i] = df[i].astype('int64')

columns = ['Weeks on Chart', 'TikTok Virality','Energy','Danceability','Acousticness']
changeFloattoInt64(columns)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4850 entries, 0 to 4849
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Artist            4850 non-null   object
 1   Streams           4850 non-null   int64 
 2   Daily Streams     4850 non-null   int64 
 3   Genre             4850 non-null   object
 4   Release Year      4850 non-null   int64 
 5   Peak Position     4850 non-null   int64 
 6   Weeks on Chart    4850 non-null   int64 
 7   Lyrics Sentiment  4850 non-null   object
 8   TikTok Virality   4850 non-null   int64 
 9   Danceability      4850 non-null   int64 
 10  Acousticness      4850 non-null   int64 
 11  Energy            4850 non-null   int64 
dtypes: int64(9), object(3)
memory usage: 454.8+ KB


In [ ]:
df['Artist'].unique()

array(['Jungkook', 'RM', 'J-Hopeft.J.Cole', 'Jimin', 'J-Hope', 'Jin', 'V',
       'Suga', 'Jungkookft.CharliePuth', 'Sugaft.IU', 'Retro Resonance',
       'Urban Rhapsody', 'Sofia Carter', 'ElectroPulse',
       'Firefly Symphony', 'Neon Vortex', 'Liam Harper', 'Jay Zenith',
       'The Midnight Howl', 'Shadow Beats', 'Samantha Lee',
       'Aurora Soundwave', 'DJ Thunder', 'Horizon Flow', 'EchoSync',
       'Ava & The Ocean', 'Crimson Echo', 'Celestial Harmony',
       'Bass Surge', 'Luna Nova'], dtype=object)

In [ ]:
df['Streams'].unique()

array([410000000, 370000000, 300000000, ..., 590393937, 376858259,
       262207213], shape=(4846,))

In [ ]:
df_clean = df.copy()

In [ ]:
def encodeCols(cols):
    for i in cols:
        temp = pd.DataFrame({i:df[i].unique()})
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(temp))
        df_clean[i] = data_LE.transform(df[i]).astype('int64')

columns = ['Artist', 'Genre', 'Lyrics Sentiment','TikTok Virality']
encodeCols(columns)

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4850 entries, 0 to 4849
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artist            4850 non-null   int64
 1   Streams           4850 non-null   int64
 2   Daily Streams     4850 non-null   int64
 3   Genre             4850 non-null   int64
 4   Release Year      4850 non-null   int64
 5   Peak Position     4850 non-null   int64
 6   Weeks on Chart    4850 non-null   int64
 7   Lyrics Sentiment  4850 non-null   int64
 8   TikTok Virality   4850 non-null   int64
 9   Danceability      4850 non-null   int64
 10  Acousticness      4850 non-null   int64
 11  Energy            4850 non-null   int64
dtypes: int64(12)
memory usage: 454.8 KB


In [ ]:
df_clean.head()

Artist    Streams  Daily Streams  Genre  Release Year  Peak Position  \
0      15  410000000         550000     19          2023             11   
1      15  370000000         520000     21          2023             13   
2      20  300000000         370000      0          2024             15   
3      11  720000000         950000      9          2023              5   
4      13  680000000         800000      7          2023              3   

   Weeks on Chart  Lyrics Sentiment  TikTok Virality  Danceability  \
0             110                 7               77             0   
1             100                 0               98             0   
2              40                 9               65             0   
3              24                 8               73             0   
4              77                12               49             0   

   Acousticness  Energy  
0             0       0  
1             0       0  
2             0       0  
3             0       0  
4             0       0

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4850 entries, 0 to 4849
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artist            4850 non-null   int64
 1   Streams           4850 non-null   int64
 2   Daily Streams     4850 non-null   int64
 3   Genre             4850 non-null   int64
 4   Release Year      4850 non-null   int64
 5   Peak Position     4850 non-null   int64
 6   Weeks on Chart    4850 non-null   int64
 7   Lyrics Sentiment  4850 non-null   int64
 8   TikTok Virality   4850 non-null   int64
 9   Danceability      4850 non-null   int64
 10  Acousticness      4850 non-null   int64
 11  Energy            4850 non-null   int64
dtypes: int64(12)
memory usage: 454.8 KB


In [ ]:
df_clean.to_csv(r'billboard_trends_cleaned.csv', index=False, header=True)

In [ ]:
df_clean['Genre'].unique()

array([19, 21,  0,  9,  7,  1, 31, 23, 24, 10, 13, 20, 22, 28,  2, 16, 32,
       33, 27, 34, 14, 25, 30,  6, 11,  8, 29,  3, 17, 18, 12,  4, 26, 15,
        5])

In [ ]:
df_clean['TikTok Virality'].unique()

array([ 77,  98,  65,  73,  49,  33,  56,  44,  32,  47,  62,  54,  25,
        45,  76,  67,  70,  50,  11,  71,  15,  87,  35,  82,  66,  16,
        12,  10,   2,  38,   4,  78,  61,  26,  21,  42,  41,  96,  27,
        89,  74,  34,  58,  59,  24,  17,  46,  40,  68,  37,   1,  57,
        19,  80,   7,  63,   0,  55,  39,  14,  29,  60,  95,  94,  90,
        20,  69,  31,  52,  75,  86,  64,   8, 100,  72,   3,  28,  97,
        99,   6,  51,  85,  93,  81,   5,  30,   9,  79,  36,  22,  84,
        92,  91,  53,  83,  48,  13,  43,  23,  18,  88])

In [ ]:
df_clean['Artist'].unique()

array([15, 20, 11, 13, 10, 14, 29, 25, 16, 26, 21, 28, 24,  7,  8, 19, 17,
       12, 27, 23, 22,  0,  5,  9,  6,  1,  4,  3,  2, 18])

In [ ]:
df_clean['Release Year'].unique()

array([2023, 2024, 1992, 2000, 2001, 2025, 1991, 2014, 2022, 1996, 2018,
       2021, 2002, 2013, 2020, 2007, 2012, 1994, 1990, 2010, 2011, 2003,
       1998, 1997, 2015, 2004, 2006, 2016, 2017, 2009, 1995, 2019, 1993,
       2008, 2005, 1999])

In [ ]:
df_clean.head(2)

Artist    Streams  Daily Streams  Genre  Release Year  Peak Position  \
0      15  410000000         550000     19          2023             11   
1      15  370000000         520000     21          2023             13   

   Weeks on Chart  Lyrics Sentiment  TikTok Virality  Danceability  \
0             110                 7               77             0   
1             100                 0               98             0   

   Acousticness  Energy  
0             0       0  
1             0       0

In [ ]:
X = df_clean[['Genre', 'TikTok Virality','Release Year']]
Y = df_clean[['Artist']]

In [ ]:
trainX, testX, trainY, testY = train_test_split(X, Y, test_size=0.2, shuffle=False)

In [ ]:
trainX.head(2)

Genre  TikTok Virality  Release Year
0     19               77          2023
1     21               98          2023

In [ ]:
trainY.head(2)

Artist
0      15
1      15

In [ ]:
import pickle
from sklearn.svm import SVC


In [ ]:
model_SVC = SVC()
model_SVC.fit(trainX, trainY)
pickle.dump(model_SVC, open('model_svc.pkl', 'wb'))
print(model_SVC)

C:\Users\LDA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()


In [ ]:
model_SVC = pickle.load(open('model_svc.pkl', 'rb'))
svr_predictions = model_SVC.predict(testX)

In [ ]:
print(svr_predictions)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, accuracy_score
 

svc_predictions_rounded = svr_predictions.round().astype(int)

# Calculate accuracy
svc_accuracy = accuracy_score(testY, svc_predictions_rounded)
print("Mean Squared Error: ", mean_squared_error(testY, svc_predictions_rounded))

Mean Squared Error:  80.59175257731958
